@echo off
echo 🚀 Εκκίνηση export του Layera codebase...

:: Παράμετροι (μπορείς να τις αλλάξεις εδώ)
set CATEGORY=RBAC
set TITLE=Authentication-System

set TIMESTAMP=%date:~-4%%date:~-10,2%%date:~-7,2%_%time:~0,2%%time:~3,2%%time:~6,2%
set TIMESTAMP=%TIMESTAMP: =0%
set OUTPUT_DIR=C:\layera_backups
set ZIP_NAME=%CATEGORY%_%TIMESTAMP%_%TITLE%.zip
set TEMP_DIR=%TEMP%\layera_export_%TIMESTAMP%

echo 📁 Συλλογή αρχείων από: C:\layera
echo 📦 Δημιουργία zip: %OUTPUT_DIR%\%ZIP_NAME%

:: Δημιουργία προσωρινού φακέλου
mkdir "%TEMP_DIR%" 2>nul

:: Αντιγραφή αρχείων εκτός από node_modules και άλλα
echo 📂 Αντιγραφή αρχείων (χωρίς node_modules, logs, κλπ)...
robocopy "C:\layera" "%TEMP_DIR%" /E /XD node_modules .git dist build lib .next .nuxt coverage .nyc_output logs .cache .temp .tmp /XF *.log *.cache npm-debug.log* yarn-debug.log* pnpm-debug.log* .DS_Store Thumbs.db *.tmp *.temp .env.local .env.production firebase-debug.log* *.zip *.tar.gz *.rar /R:0 /W:0 /NFL /NDL /NJH /NJS /NC /NS /NP

:: Δημιουργία αρχείου πληροφοριών έκδοσης
echo 📄 Δημιουργία αρχείου πληροφοριών έκδοσης...
(
echo # 📦 Layera Codebase Export
echo.
echo ## 🏷️ Στοιχεία Έκδοσης
echo - **Κατηγορία**: %CATEGORY%
echo - **Τίτλος**: %TITLE%
echo - **Ημερομηνία Export**: %date% %time%
echo - **Timestamp**: %TIMESTAMP%
echo.
echo ## 📝 Περιγραφή
echo Αυτό το αρχείο περιέχει την έκδοση του Layera codebase που εξήχθη στις %date% %time%.
echo.
echo ### 🎯 Τι περιλαμβάνεται σε αυτήν την έκδοση:
echo - Σύστημα RBAC ^(Role-Based Access Control^)
echo - Υποχρεωτικό 2FA για broker/builder/admin ρόλους
echo - Firebase Authentication με custom claims
echo - Firebase Cloud Functions για διαχείριση ρόλων
echo - React UI components για έλεγχο πρόσβασης
echo - Security rules για Firestore
echo - Testing infrastructure με Vitest + RTL
echo - Admin tools scripts για διαχείριση χρηστών
echo.
echo ### 🔧 Τεχνολογίες:
echo - React 19.1.1
echo - Firebase 12.4.0
echo - Vite 7.1.7
echo - Tailwind CSS 4.1.14
echo - Vitest 3.2.4
echo - TypeScript
echo.
echo ### 📂 Δομή Project:
echo ```
echo layera/
echo ├── apps/layera-id/          # Main React application
echo ├── functions/               # Firebase Cloud Functions
echo ├── tools/admin/            # Admin management scripts
echo ├── docs/                   # Documentation
echo ├── firestore.rules         # Security rules
echo └── export scripts          # Backup automation
echo ```
echo.
echo ### 🚀 Τρέχουσες λειτουργίες:
echo - ✅ Email verification απαιτείται για όλους τους χρήστες
echo - ✅ Ρόλοι: private, broker, builder, admin
echo - ✅ 2FA υποχρεωτικό για broker/builder/admin
echo - ✅ Custom claims στο Firebase
echo - ✅ Secure API endpoints με έλεγχο δικαιωμάτων
echo - ✅ UI components για role display και MFA enrollment
echo.
echo ### 📋 Επόμενα βήματα για deployment:
echo 1. Upgrade Firebase σε Blaze plan για Cloud Functions
echo 2. Configure Email/Password + Phone Auth στο Firebase Console
echo 3. Setup Firebase Storage για storage rules
echo 4. Deploy functions: `cd functions ^&^& npm run deploy`
echo 5. Run tests: `npm run test`
echo.
echo ---
echo **Export Date**: %date% %time%
echo **Generated by**: Layera Export Script v1.0
) > "%TEMP_DIR%\VERSION-INFO.md"

:: Δημιουργία ZIP με PowerShell
echo 🗜️ Δημιουργία ZIP αρχείου...
powershell -Command "Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::CreateFromDirectory('%TEMP_DIR%', '%OUTPUT_DIR%\%ZIP_NAME%', 'Optimal', $false)"

:: Καθαρισμός
echo 🧹 Καθαρισμός προσωρινών αρχείων...
rmdir /s /q "%TEMP_DIR%" 2>nul

:: Έλεγχος αν δημιουργήθηκε το ZIP
if exist "%OUTPUT_DIR%\%ZIP_NAME%" (
    echo ✅ Επιτυχής δημιουργία ZIP!
    echo 📍 Τοποθεσία: %OUTPUT_DIR%\%ZIP_NAME%
    echo 🔗 Άνοιγμα φακέλου backups...
    start "" explorer "%OUTPUT_DIR%"
    echo 🎉 Ολοκληρώθηκε με επιτυχία!
) else (
    echo ❌ Σφάλμα κατά τη δημιουργία του ZIP αρχείου!
)

pause