import React from 'react';
import { Box } from '@layera/layout';
import { Button } from '@layera/buttons';
import { Text } from '@layera/typography';

/**
 * ARXES COMPLIANT Export Panel Component
 *
 * Export και Reset λειτουργίες από το HTML mockup:
 * - exportCSS(): Συλλογή CSS variables και δημιουργία αρχείου
 * - resetToDefaults(): Επαναφορά στις default τιμές
 *
 * Χρησιμοποιεί υπάρχοντα tokens και @layera/* components
 */

export const ExportPanel: React.FC = () => {
  const handleExportCSS = React.useCallback(() => {
    console.log('🚀 Exporting CSS...');

    // Συλλογή CSS variables από το root element
    const root = document.documentElement;
    const cssVariables: string[] = [];

    // Get computed style
    const computedStyle = getComputedStyle(root);

    // Συλλογή live και layera variables
    for (let i = 0; i < computedStyle.length; i++) {
      const property = computedStyle[i];
      if (property.startsWith('--live-') || property.startsWith('--layera-')) {
        const value = computedStyle.getPropertyValue(property);
        cssVariables.push(`  ${property}: ${value};`);
      }
    }

    // Δημιουργία CSS περιεχομένου
    const cssContent = `:root {\n${cssVariables.join('\n')}\n}\n\n/* Generated by Layera Design Control Panel */\n/* Date: ${new Date().toISOString()} */`;

    // Δημιουργία και download αρχείου
    const blob = new Blob([cssContent], { type: 'text/css' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'layera-theme-export.css';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    console.log('✅ CSS exported successfully!');
  }, []);

  const handleResetToDefaults = React.useCallback(() => {
    console.log('🔄 Resetting to defaults...');

    // Reset στις default τιμές από το Dynamic Token System
    const root = document.documentElement;

    // Default colors
    const defaultColors = {
      '--live-primary-color': '#4A90E2',
      '--live-secondary-color': '#9013FE',
      '--live-success-color': '#4CAF50',
      '--live-warning-color': '#FF9800',
      '--live-danger-color': '#F44336',
      '--live-info-color': '#2196F3'
    };

    // Default layout values
    const defaultLayout = {
      '--live-component-gap': '16px',
      '--live-padding': '16px',
      '--live-button-padding': '16px',
      '--live-font-size': '16px',
      '--live-border-radius': '8px'
    };

    // Εφαρμογή default τιμών
    Object.entries({ ...defaultColors, ...defaultLayout }).forEach(([property, value]) => {
      root.style.setProperty(property, value);
    });

    // Trigger re-render events για να ενημερωθούν τα components
    window.dispatchEvent(new CustomEvent('layera:theme-reset'));

    console.log('✅ Reset completed successfully!');
  }, []);

  return (
    <Box className="layera-flex layera-flex--direction-column layera-flex--gap-md">
      <Text
        className="layera-typography layera-margin-bottom--sm"
        data-size="sm"
        data-color="secondary"
      >
        Εξαγωγή ρυθμίσεων και επαναφορά στις αρχικές τιμές
      </Text>

      <Box className="layera-flex layera-flex--gap-sm">
        <Button
          variant="info"
          size="sm"
          onClick={handleExportCSS}
          className="layera-button layera-flex--grow"
        >
          💾 Export CSS
        </Button>

        <Button
          variant="warning"
          size="sm"
          onClick={handleResetToDefaults}
          className="layera-button layera-flex--grow"
        >
          🔄 Reset
        </Button>
      </Box>

      <Text
        className="layera-typography"
        data-size="xs"
        data-color="secondary"
      >
        Το Export δημιουργεί .css αρχείο με τις τρέχουσες ρυθμίσεις.
        Το Reset επαναφέρει όλες τις τιμές στις αρχικές.
      </Text>
    </Box>
  );
};